#  _                      _            _    
# | |__  _   _ _ __  _ __| | ___   ___| | __
# | '_ \| | | | '_ \| '__| |/ _ \ / __| |/ /
# | | | | |_| | |_) | |  | | (_) | (__|   < 
# |_| |_|\__, | .__/|_|  |_|\___/ \___|_|\_\
#        |___/|_|                            

general {
    no_fade_in = false
    grace = 0
    disable_loading = true
}

background {
    monitor =
    path = screenshot
    color = rgba(12, 12, 12, 1.0)
    blur_passes = 3
    blur_size = 7
}

# TIME
label {
    monitor =
    text = cmd[update:1000] echo "$(date +"%H:%M")"
    color = rgba(211, 54, 55, 1.0)
    font_size = 120
    font_family = SpaceMono Nerd Font Bold
    position = 0, -300
    halign = center
    valign = top
}

# DATE
label {
    monitor =
    text = cmd[update:1000] echo "$(date +"%A, %d %B")"
    color = rgba(172, 126, 124, 1.0)
    font_size = 25
    font_family = SpaceMono Nerd Font
    position = 0, -520
    halign = center
    valign = top
}

# WEATHER
label {
    monitor =
    text = cmd[update:3600000] echo "$(curl -s 'wttr.in?format=%c%t')"
    color = rgba(172, 126, 124, 1.0)
    font_size = 20
    font_family = SpaceMono Nerd Font
    position = 50, 50
    halign = left
    valign = bottom
}

# RANDOM PHRASE
label {
    monitor =
    text = cmd[update:0] echo "$(~/.config/niri/scripts/random_phrase.sh)"
    color = rgba(172, 126, 124, 0.6)
    font_size = 14
    font_family = SpaceMono Nerd Font Italic
    position = 0, 50
    halign = center
    valign = bottom
}

# DYNAMIC FAIL MESSAGE
label {
    monitor =
    text = cmd[update:100] echo "$(~/.config/niri/scripts/fail_text.sh $ATTEMPTS)"
    color = rgba(211, 54, 55, 1.0)
    font_size = 16
    font_family = SpaceMono Nerd Font Bold
    position = 0, -170
    halign = center
    valign = center
}

# INPUT FIELD
input-field {
    monitor =
    size = 250, 60
    outline_thickness = 2
    dots_size = 0.2
    dots_spacing = 0.2
    dots_center = true
    outer_color = rgba(53, 18, 18, 1.0)
    inner_color = rgba(12, 12, 12, 1.0)
    font_color = rgba(211, 54, 55, 1.0)
    fade_on_empty = false
    font_family = SpaceMono Nerd Font
    placeholder_text = <span foreground="##ac7e7c">Identify yourself...</span>
    hide_input = false
    fail_text = 
    fail_color = rgba(211, 54, 55, 1.0)
    position = 0, -100
    halign = center
    valign = center
}
